### Sudoku Solver

Solver a partir de df

In [1]:
import pandas as pd
import numpy as np

Se necesitan 3 data frames

1.- La matriz entera
2.- Para cada cuadro
3.- Para cada celda

In [107]:
All_possible_values = set(np.linspace(1,9,9, dtype=int))

In [108]:
def celda(juego, squares):
    celda = {}
    for square in range(len(squares)):
        for row in range(3):
            for column in range(3):
                Value = squares[square][row][column]
                fila = row + (square//3)*3
                columna = column + (square%3)*3
                celda_idx = fila * 9 + columna
                if Value == 0:
                    possible_values =All_possible_values - set((possible__values_row(juego, fila) 
                                           | possible__values_column(juego, columna) 
                                           | possible_values_square(squares[square])))
                else:
                    possible_values = 0
                celda[celda_idx] = {"Value": Value, 
                            "Square": square, 
                            "Row": fila,
                            "Column": columna,
                            "Possible Values": possible_values
                        }
    return celda

def square(juego):
    square = {}
    for i in range(3):
        for j in range(3):
            square_num = i*3+j
            celda_values = juego.iloc[i*3:(i+1)*3, j*3:(j+1)*3].values
            square[square_num] = celda_values
    return square

def possible__values_row(juego, row):
    row_values = juego.iloc[row, :].values
    return set([x for x in row_values if x != 0])

def possible__values_column(juego, column):
    column_values = juego.iloc[:, column].values
    return set([x for x in column_values if x != 0])

def possible_values_square(square):
    square_values = square.flatten()
    return set([x for x in square_values if x != 0])

In [109]:
def imprimir_juego(juego):
    print("-------------------------","\n")
    for i in range(juego.shape[0]):
        print("|", end=" ")
        for j in range(juego.shape[1]):
            print(juego.iloc[i,j], end=" ")
            if (j+1) % 3 == 0: print("|", end=" ")
        print("\n")
        if (i+2) % 3 == 1: print("-------------------------","\n")

In [110]:
juego = pd.read_csv('juego.csv', header=None)
imprimir_juego(juego)

-------------------------

| 5 3 0 | 0 7 0 | 0 0 0 |

| 6 0 0 | 1 9 5 | 0 0 0 |

| 0 0 8 | 0 0 0 | 0 6 0 |

-------------------------

| 8 0 0 | 0 6 0 | 0 0 3 |

| 4 0 0 | 8 0 3 | 0 0 1 |

| 7 0 0 | 0 2 0 | 0 0 6 |

-------------------------

| 0 6 0 | 0 0 0 | 2 8 0 |

| 0 0 0 | 4 1 9 | 0 0 5 |

| 0 0 0 | 0 8 0 | 0 7 9 |

-------------------------

In [111]:
squares = square(juego)
celdas = celda(juego, squares)
celdas

{0: {'Value': np.int64(5),
  'Square': 0,
  'Row': 0,
  'Column': 0,
  'Possible Values': 0},
 1: {'Value': np.int64(3),
  'Square': 0,
  'Row': 0,
  'Column': 1,
  'Possible Values': 0},
 2: {'Value': np.int64(0),
  'Square': 0,
  'Row': 0,
  'Column': 2,
  'Possible Values': {np.int64(1), np.int64(2), np.int64(4), np.int64(9)}},
 9: {'Value': np.int64(6),
  'Square': 0,
  'Row': 1,
  'Column': 0,
  'Possible Values': 0},
 10: {'Value': np.int64(0),
  'Square': 0,
  'Row': 1,
  'Column': 1,
  'Possible Values': {np.int64(2), np.int64(4), np.int64(7)}},
 11: {'Value': np.int64(0),
  'Square': 0,
  'Row': 1,
  'Column': 2,
  'Possible Values': {np.int64(2), np.int64(4), np.int64(7)}},
 18: {'Value': np.int64(0),
  'Square': 0,
  'Row': 2,
  'Column': 0,
  'Possible Values': {np.int64(1), np.int64(2), np.int64(9)}},
 19: {'Value': np.int64(0),
  'Square': 0,
  'Row': 2,
  'Column': 1,
  'Possible Values': {np.int64(1),
   np.int64(2),
   np.int64(4),
   np.int64(7),
   np.int64(9)}},
 20: {'Value': np.int64(8),
  'Square': 0,
  'Row': 2,
  'Column': 2,
  'Possible Values': 0},
 3: {'Value': np.int64(0),
  'Square': 1,
  'Row': 0,
  'Column': 3,
  'Possible Values': {np.int64(2), np.int64(6)}},
 4: {'Value': np.int64(7),
  'Square': 1,
  'Row': 0,
  'Column': 4,
  'Possible Values': 0},
 5: {'Value': np.int64(0),
  'Square': 1,
  'Row': 0,
  'Column': 5,
  'Possible Values': {np.int64(2), np.int64(4), np.int64(6), np.int64(8)}},
 12: {'Value': np.int64(1),
  'Square': 1,
  'Row': 1,
  'Column': 3,
  'Possible Values': 0},
 13: {'Value': np.int64(9),
  'Square': 1,
  'Row': 1,
  'Column': 4,
  'Possible Values': 0},
 14: {'Value': np.int64(5),
  'Square': 1,
  'Row': 1,
  'Column': 5,
  'Possible Values': 0},
 21: {'Value': np.int64(0),
  'Square': 1,
  'Row': 2,
  'Column': 3,
  'Possible Values': {np.int64(2), np.int64(3)}},
 22: {'Value': np.int64(0),
  'Square': 1,
  'Row': 2,
  'Column': 4,
  'Possible Values': {np.int64(3), np.int64(4)}},
 23: {'Value': np.int64(0),
  'Square': 1,
  'Row': 2,
  'Column': 5,
  'Possible Values': {np.int64(2), np.int64(4)}},
 6: {'Value': np.int64(0),
  'Square': 2,
  'Row': 0,
  'Column': 6,
  'Possible Values': {np.int64(1), np.int64(4), np.int64(8), np.int64(9)}},
 7: {'Value': np.int64(0),
  'Square': 2,
  'Row': 0,
  'Column': 7,
  'Possible Values': {np.int64(1), np.int64(2), np.int64(4), np.int64(9)}},
 8: {'Value': np.int64(0),
  'Square': 2,
  'Row': 0,
  'Column': 8,
  'Possible Values': {np.int64(2), np.int64(4), np.int64(8)}},
 15: {'Value': np.int64(0),
  'Square': 2,
  'Row': 1,
  'Column': 6,
  'Possible Values': {np.int64(3), np.int64(4), np.int64(7), np.int64(8)}},
 16: {'Value': np.int64(0),
  'Square': 2,
  'Row': 1,
  'Column': 7,
  'Possible Values': {np.int64(2), np.int64(3), np.int64(4)}},
 17: {'Value': np.int64(0),
  'Square': 2,
  'Row': 1,
  'Column': 8,
  'Possible Values': {np.int64(2), np.int64(4), np.int64(7), np.int64(8)}},
 24: {'Value': np.int64(0),
  'Square': 2,
  'Row': 2,
  'Column': 6,
  'Possible Values': {np.int64(1),
   np.int64(3),
   np.int64(4),
   np.int64(5),
   np.int64(7),
   np.int64(9)}},
 25: {'Value': np.int64(6),
  'Square': 2,
  'Row': 2,
  'Column': 7,
  'Possible Values': 0},
 26: {'Value': np.int64(0),
  'Square': 2,
  'Row': 2,
  'Column': 8,
  'Possible Values': {np.int64(2), np.int64(4), np.int64(7)}},
 27: {'Value': np.int64(8),
  'Square': 3,
  'Row': 3,
  'Column': 0,
  'Possible Values': 0},
 28: {'Value': np.int64(0),
  'Square': 3,
  'Row': 3,
  'Column': 1,
  'Possible Values': {np.int64(1), np.int64(2), np.int64(5), np.int64(9)}},
 29: {'Value': np.int64(0),
  'Square': 3,
  'Row': 3,
  'Column': 2,
  'Possible Values': {np.int64(1), np.int64(2), np.int64(5), np.int64(9)}},
 36: {'Value': np.int64(4),
  'Square': 3,
  'Row': 4,
  'Column': 0,
  'Possible Values': 0},
 37: {'Value': np.int64(0),
  'Square': 3,
  'Row': 4,
  'Column': 1,
  'Possible Values': {np.int64(2), np.int64(5), np.int64(9)}},
 38: {'Value': np.int64(0),
  'Square': 3,
  'Row': 4,
  'Column': 2,
  'Possible Values': {np.int64(2), np.int64(5), np.int64(6), np.int64(9)}},
 45: {'Value': np.int64(7),
  'Square': 3,
  'Row': 5,
  'Column': 0,
  'Possible Values': 0},
 46: {'Value': np.int64(0),
  'Square': 3,
  'Row': 5,
  'Column': 1,
  'Possible Values': {np.int64(1), np.int64(5), np.int64(9)}},
 47: {'Value': np.int64(0),
  'Square': 3,
  'Row': 5,
  'Column': 2,
  'Possible Values': {np.int64(1), np.int64(3), np.int64(5), np.int64(9)}},
 30: {'Value': np.int64(0),
  'Square': 4,
  'Row': 3,
  'Column': 3,
  'Possible Values': {np.int64(5), np.int64(7), np.int64(9)}},
 31: {'Value': np.int64(6),
  'Square': 4,
  'Row': 3,
  'Column': 4,
  'Possible Values': 0},
 32: {'Value': np.int64(0),
  'Square': 4,
  'Row': 3,
  'Column': 5,
  'Possible Values': {np.int64(1), np.int64(4), np.int64(7)}},
 39: {'Value': np.int64(8),
  'Square': 4,
  'Row': 4,
  'Column': 3,
  'Possible Values': 0},
 40: {'Value': np.int64(0),
  'Square': 4,
  'Row': 4,
  'Column': 4,
  'Possible Values': {np.int64(5)}},
 41: {'Value': np.int64(3),
  'Square': 4,
  'Row': 4,
  'Column': 5,
  'Possible Values': 0},
 48: {'Value': np.int64(0),
  'Square': 4,
  'Row': 5,
  'Column': 3,
  'Possible Values': {np.int64(5), np.int64(9)}},
 49: {'Value': np.int64(2),
  'Square': 4,
  'Row': 5,
  'Column': 4,
  'Possible Values': 0},
 50: {'Value': np.int64(0),
  'Square': 4,
  'Row': 5,
  'Column': 5,
  'Possible Values': {np.int64(1), np.int64(4)}},
 33: {'Value': np.int64(0),
  'Square': 5,
  'Row': 3,
  'Column': 6,
  'Possible Values': {np.int64(4), np.int64(5), np.int64(7), np.int64(9)}},
 34: {'Value': np.int64(0),
  'Square': 5,
  'Row': 3,
  'Column': 7,
  'Possible Values': {np.int64(2), np.int64(4), np.int64(5), np.int64(9)}},
 35: {'Value': np.int64(3),
  'Square': 5,
  'Row': 3,
  'Column': 8,
  'Possible Values': 0},
 42: {'Value': np.int64(0),
  'Square': 5,
  'Row': 4,
  'Column': 6,
  'Possible Values': {np.int64(5), np.int64(7), np.int64(9)}},
 43: {'Value': np.int64(0),
  'Square': 5,
  'Row': 4,
  'Column': 7,
  'Possible Values': {np.int64(2), np.int64(5), np.int64(9)}},
 44: {'Value': np.int64(1),
  'Square': 5,
  'Row': 4,
  'Column': 8,
  'Possible Values': 0},
 51: {'Value': np.int64(0),
  'Square': 5,
  'Row': 5,
  'Column': 6,
  'Possible Values': {np.int64(4), np.int64(5), np.int64(8), np.int64(9)}},
 52: {'Value': np.int64(0),
  'Square': 5,
  'Row': 5,
  'Column': 7,
  'Possible Values': {np.int64(4), np.int64(5), np.int64(9)}},
 53: {'Value': np.int64(6),
  'Square': 5,
  'Row': 5,
  'Column': 8,
  'Possible Values': 0},
 54: {'Value': np.int64(0),
  'Square': 6,
  'Row': 6,
  'Column': 0,
  'Possible Values': {np.int64(1), np.int64(3), np.int64(9)}},
 55: {'Value': np.int64(6),
  'Square': 6,
  'Row': 6,
  'Column': 1,
  'Possible Values': 0},
 56: {'Value': np.int64(0),
  'Square': 6,
  'Row': 6,
  'Column': 2,
  'Possible Values': {np.int64(1),
   np.int64(3),
   np.int64(4),
   np.int64(5),
   np.int64(7),
   np.int64(9)}},
 63: {'Value': np.int64(0),
  'Square': 6,
  'Row': 7,
  'Column': 0,
  'Possible Values': {np.int64(2), np.int64(3)}},
 64: {'Value': np.int64(0),
  'Square': 6,
  'Row': 7,
  'Column': 1,
  'Possible Values': {np.int64(2), np.int64(7), np.int64(8)}},
 65: {'Value': np.int64(0),
  'Square': 6,
  'Row': 7,
  'Column': 2,
  'Possible Values': {np.int64(2), np.int64(3), np.int64(7)}},
 72: {'Value': np.int64(0),
  'Square': 6,
  'Row': 8,
  'Column': 0,
  'Possible Values': {np.int64(1), np.int64(2), np.int64(3)}},
 73: {'Value': np.int64(0),
  'Square': 6,
  'Row': 8,
  'Column': 1,
  'Possible Values': {np.int64(1), np.int64(2), np.int64(4), np.int64(5)}},
 74: {'Value': np.int64(0),
  'Square': 6,
  'Row': 8,
  'Column': 2,
  'Possible Values': {np.int64(1),
   np.int64(2),
   np.int64(3),
   np.int64(4),
   np.int64(5)}},
 57: {'Value': np.int64(0),
  'Square': 7,
  'Row': 6,
  'Column': 3,
  'Possible Values': {np.int64(3), np.int64(5), np.int64(7)}},
 58: {'Value': np.int64(0),
  'Square': 7,
  'Row': 6,
  'Column': 4,
  'Possible Values': {np.int64(3), np.int64(5)}},
 59: {'Value': np.int64(0),
  'Square': 7,
  'Row': 6,
  'Column': 5,
  'Possible Values': {np.int64(7)}},
 66: {'Value': np.int64(4),
  'Square': 7,
  'Row': 7,
  'Column': 3,
  'Possible Values': 0},
 67: {'Value': np.int64(1),
  'Square': 7,
  'Row': 7,
  'Column': 4,
  'Possible Values': 0},
 68: {'Value': np.int64(9),
  'Square': 7,
  'Row': 7,
  'Column': 5,
  'Possible Values': 0},
 75: {'Value': np.int64(0),
  'Square': 7,
  'Row': 8,
  'Column': 3,
  'Possible Values': {np.int64(2), np.int64(3), np.int64(5), np.int64(6)}},
 76: {'Value': np.int64(8),
  'Square': 7,
  'Row': 8,
  'Column': 4,
  'Possible Values': 0},
 77: {'Value': np.int64(0),
  'Square': 7,
  'Row': 8,
  'Column': 5,
  'Possible Values': {np.int64(2), np.int64(6)}},
 60: {'Value': np.int64(2),
  'Square': 8,
  'Row': 6,
  'Column': 6,
  'Possible Values': 0},
 61: {'Value': np.int64(8),
  'Square': 8,
  'Row': 6,
  'Column': 7,
  'Possible Values': 0},
 62: {'Value': np.int64(0),
  'Square': 8,
  'Row': 6,
  'Column': 8,
  'Possible Values': {np.int64(4)}},
 69: {'Value': np.int64(0),
  'Square': 8,
  'Row': 7,
  'Column': 6,
  'Possible Values': {np.int64(3), np.int64(6)}},
 70: {'Value': np.int64(0),
  'Square': 8,
  'Row': 7,
  'Column': 7,
  'Possible Values': {np.int64(3)}},
 71: {'Value': np.int64(5),
  'Square': 8,
  'Row': 7,
  'Column': 8,
  'Possible Values': 0},
 78: {'Value': np.int64(0),
  'Square': 8,
  'Row': 8,
  'Column': 6,
  'Possible Values': {np.int64(1), np.int64(3), np.int64(4), np.int64(6)}},
 79: {'Value': np.int64(7),
  'Square': 8,
  'Row': 8,
  'Column': 7,
  'Possible Values': 0},
 80: {'Value': np.int64(9),
  'Square': 8,
  'Row': 8,
  'Column': 8,
  'Possible Values': 0}}

In [112]:
def solver(juego, celdas):
    for celda_idx, celda_info in celdas.items():
        if celda_info["Value"] == 0 and len(celda_info["Possible Values"]) == 1:
            value_to_fill = celda_info["Possible Values"]
            row = celda_info["Row"]
            column = celda_info["Column"]
            juego.iloc[row, column] = value_to_fill
            print(f"Filled cell at row {row}, column {column} with value {value_to_fill}.")
    return juego

juego = solver(juego, celdas)
juego

Filled cell at row 4, column 4 with value {np.int64(5)}.
Filled cell at row 6, column 5 with value {np.int64(7)}.
Filled cell at row 6, column 8 with value {np.int64(4)}.
Filled cell at row 7, column 7 with value {np.int64(3)}.

   0  1  2  3  4  5  6  7  8
0  5  3  0  0  7  0  0  0  0
1  6  0  0  1  9  5  0  0  0
2  0  0  8  0  0  0  0  6  0
3  8  0  0  0  6  0  0  0  3
4  4  0  0  8  5  3  0  0  1
5  7  0  0  0  2  0  0  0  6
6  0  6  0  0  0  7  2  8  4
7  0  0  0  4  1  9  0  3  5
8  0  0  0  0  8  0  0  7  9

In [113]:
squares = square(juego)
celdas = celda(juego, squares)
juego = solver(juego, celdas)
juego

Filled cell at row 5, column 3 with value {np.int64(9)}.
Filled cell at row 7, column 0 with value {np.int64(2)}.
Filled cell at row 6, column 4 with value {np.int64(3)}.
Filled cell at row 7, column 6 with value {np.int64(6)}.

   0  1  2  3  4  5  6  7  8
0  5  3  0  0  7  0  0  0  0
1  6  0  0  1  9  5  0  0  0
2  0  0  8  0  0  0  0  6  0
3  8  0  0  0  6  0  0  0  3
4  4  0  0  8  5  3  0  0  1
5  7  0  0  9  2  0  0  0  6
6  0  6  0  0  3  7  2  8  4
7  2  0  0  4  1  9  6  3  5
8  0  0  0  0  8  0  0  7  9

In [121]:
import pandas as pd
import numpy as np

All_possible_values = set(np.linspace(1,9,9, dtype=int))

def celda(juego, squares):
    celda = {}
    for square in range(len(squares)):
        for row in range(3):
            for column in range(3):
                Value = squares[square][row][column]
                fila = row + (square//3)*3
                columna = column + (square%3)*3
                celda_idx = fila * 9 + columna
                if Value == 0:
                    possible_values =All_possible_values - set((possible__values_row(juego, fila) 
                                           | possible__values_column(juego, columna) 
                                           | possible_values_square(squares[square])))
                else:
                    possible_values = set()
                celda[celda_idx] = {"Value": Value, 
                            "Square": square, 
                            "Row": fila,
                            "Column": columna,
                            "Possible Values": possible_values
                        }
    return celda

def square(juego):
    square = {}
    for i in range(3):
        for j in range(3):
            square_num = i*3+j
            celda_values = juego.iloc[i*3:(i+1)*3, j*3:(j+1)*3].values
            square[square_num] = celda_values
    return square

def possible__values_row(juego, row):
    row_values = juego.iloc[row, :].values
    return set([x for x in row_values if x != 0])

def possible__values_column(juego, column):
    column_values = juego.iloc[:, column].values
    return set([x for x in column_values if x != 0])

def possible_values_square(square):
    square_values = square.flatten()
    return set([x for x in square_values if x != 0])

def possible_update(celdas,row,col,squa,val):
    for info in celdas.values():
        if info["Row"]==row or info["Column"] == col or info["Square"] == squa:
            info["Possible Values"].discard(val)

def imprimir_juego(juego):
    print("-------------------------","\n")
    for i in range(juego.shape[0]):
        print("|", end=" ")
        for j in range(juego.shape[1]):
            print(juego.iloc[i,j], end=" ")
            if (j+1) % 3 == 0: print("|", end=" ")
        print("\n")
        if (i+2) % 3 == 1: print("-------------------------","\n")

def solver(juego, celdas):
    cambios = False
    for celda_idx, celda_info in celdas.items():
        if celda_info["Value"] == 0 and len(celda_info["Possible Values"]) == 1:
            value_to_fill = celda_info["Possible Values"].pop()
            row = celda_info["Row"]
            column = celda_info["Column"]
            sq_n = celda_info["Square"]
            juego.iloc[row, column] = value_to_fill
            print(f"Filled cell at row {row}, column {column} with value {value_to_fill}.")
            possible_update(celdas,row,column,square,value_to_fill)
            cambios = True
    return juego, cambios

def hidden(juego, celdas):
    cambios = False
    for idx, info in celdas.items():
        if info["Possible Values"] == set():
            continue
        
        fila, columna, squ = info["Row"], info["Column"], info["Square"]
        check_squ -= info["Possible Values"].copy()
        check_row -= info["Possible Values"].copy()
        check_col -= info["Possible Values"].copy()
        
        for idx_c, info_c in celdas.items():
            
            if info_c["Possible Values"] == set() or idx == idx_c:
                continue

            if info_c["Square"] == squ:
                check_squ -= info_c["Possible Values"]
            if info_c["Row"] == fila:
                check_row -= info_c["Possible Values"]
            if info_c["Column"] == columna:
                check_col -= info_c["Possible Values"]

        for check in (check_squ, check_row, check_col):
            if  len(check) == 1:
                valor = check.pop()
                juego.iloc[fila, columna] = valor
                print(f"Filled cell at row {fila}, column {columna} with value {valor}.")
                celdas[idx]["Possible Values"]=set()
                possible_update(celdas,fila,columna,squ,valor)
                cambios = True
                break
    return juego, cambios
                        

def resuelto(juego):
    return not (juego==0).any().any()

juego = pd.read_csv('juego_test_0.csv', header=None)
imprimir_juego(juego)

cambios = True
squares = square(juego)
celdas = celda(juego, squares)
juego, cambios = solver(juego, celdas)

while cambios and not resuelto(juego):
    squares = square(juego)
    celdas = celda(juego, squares)
    juego, cambios_single = solver(juego, celdas)
    
    squares = square(juego)
    celdas = celda(juego, squares)
    juego, cambios_hidden = hidden(juego, celdas)
    
    cambios = cambios_single or cambios_hidden
imprimir_juego(juego)

if resuelto(juego):
    print("Solucionado con single search")
else:
    print("Procedo a usar hidden values")

juego.to_csv("Juego_resuelto.csv", index=False, header=False)

-------------------------

| 0 9 0 | 0 0 1 | 2 0 0 |

| 0 3 0 | 0 2 8 | 4 0 6 |

| 0 6 0 | 0 0 0 | 0 8 0 |

-------------------------

| 0 7 0 | 0 0 0 | 1 4 0 |

| 0 2 0 | 0 5 0 | 7 0 0 |

| 0 0 3 | 0 0 0 | 0 0 2 |

-------------------------

| 0 1 0 | 9 0 0 | 0 0 0 |

| 0 0 0 | 7 0 5 | 0 0 0 |

| 0 8 7 | 2 0 6 | 0 0 4 |

-------------------------

Filled cell at row 1, column 3 with value 5.
Filled cell at row 7, column 1 with value 4.
Filled cell at row 1, column 2 with value 1.
Filled cell at row 5, column 1 with value 5.

UnboundLocalError: cannot access local variable 'check_squ' where it is not associated with a value

In [ ]:
import numpy as np
import pandas as pd
import os
import random

def string_to(question_str):
    valores = ['0' if c == '.' else int(c) for c in question_str]
    matriz = np.array(valores).reshape(9,9)
    return pd.DataFrame(matriz)

def extraer_juego(file):
    juego = pd.read_csv(file) 
    juego = juego['question']
    n = random.choice(range(len(juego)))
    print(f"Se cargo la partida {n} de la base de datos")
    juego = string_to(juego.loc[n])
    return juego

extraer_juego(test.csv)

In [1]:
import pandas as pd

ruta_bd = "test_orig.csv"
juego = pd.read_csv(ruta_bd)
juego = juego['question']
juego.to_csv("test.csv",index=False,header=False)